# Generated by Django 5.2.8 on 2025-11-17 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید دقیقاً ۱۰ رقم باشد.')], verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره همراه باید با 09 شروع شود و 11 رقم باشد.')], verbose_name='شماره همراه')),
                ('file_number', models.CharField(max_length=20, unique=True, verbose_name='شماره پرونده')),
            ],
        ),
    ]
