# Generated by Django 5.2.8 on 2025-12-16 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalfile',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='generalfile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره همراه باید با 09 شروع شود و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره همراه'),
        ),
    ]
